### ISSUE TITLE
seu site nao esta tendo link direto com seu github

### ISSUE THREAD

**Issue by lopesmathe** [AldairRocha/Projeto-cordel#1]
Na parte do footer ele tem assim "Site criado por [Aldair Santos Rocha](https://aldairrocha.github.io/) para conhecimento" porém quando aperto no seu nome aparece q a pag esta off

**Comment by lopesmathe** [comment]
vdd, esqueci de falar, oq esta dando erro é no repositorio chamado "refazendo" (é o primeiro arquivo index)

**Comment by AldairRocha** [comment]
tendi vlw
